name: salesgo_agent
description: SalesGO agent mobil ilova
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.0.2
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

# Launcher ikon (build vaqtida tools/make_icon.py yasaydi)
flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0F766E"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  min_sdk_android: 21
